version: "3.8"

services:
  lanshare:
    image: zhong12138/lanshare:latest
    ports:
      - "7070:7070"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - DOCKER_CONTAINER=true
      - HOST_IP=192.168.1.100
      - DOCKER_HOST_IP=192.168.1.100
