version: '3.8'
services:
  lanshare:
    image: zhong12138/lanshare:latest
    ports:
      - "7070:7070"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - DOCKER_CONTAINER=true
      - HOST_IP=${HOST_IP:-}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-}
