# LanShare - 局域网文件共享
version: "3.8"

services:
  lanshare:
    build: .
    image: lanshare-local:latest
    ports:
      - "7070:7070"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - HOST_IP=192.168.1.100
      - DOCKER_HOST_IP=192.168.1.100
      - DOCKER_CONTAINER=true
      - HOST_IP=${HOST_IP:-}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-}